# LSTM Neural Network for Time Series Prediction

from: http://www.jakob-aungiers.com/articles/a/LSTM-Neural-Network-for-Time-Series-Prediction

## 1. Plot the data to learn from

The data is provided by Jakob to be downloaded from <a href="https://raw.githubusercontent.com/jaungiers/LSTM-Neural-Network-for-Time-Series-Prediction/master/sinwave.csv"> here </a>, the graph should look like the one shown below:


<img src="http://www.jakob-aungiers.com/img/article/lstm-neural-network-timeseries/sindata.png">

The code to load and plot is also provided: 

In [2]:
import numpy as np

def load_data(filename, seq_len, normalise_window):
    f = open(filename, 'rb').read()
    data = f.decode().split('\n')

    sequence_length = seq_len + 1
    result = []
    for index in range(len(data) - sequence_length):
        result.append(data[index: index + sequence_length])

    result = np.array(result)

    row = round(0.9 * result.shape[0])
    train = result[:int(row), :]
    np.random.shuffle(train)
    x_train = train[:, :-1]
    y_train = train[:, -1]
    x_test = result[int(row):, :-1]
    y_test = result[int(row):, -1]

    x_train = np.reshape(x_train, (x_train.shape[0], x_train.shape[1], 1))
    x_test = np.reshape(x_test, (x_test.shape[0], x_test.shape[1], 1))  

    return [x_train, y_train, x_test, y_test]

### 1.1 Analysing the load and plot function:

In [3]:
path_data = 'sinwave.csv'


f = open(path_data, 'rb').read()

In [4]:
type(f)

bytes

In [ ]:
f

<img src="imgs/f_info.jpeg">

#### 1.1.1 What does f.decode() ?

##### 1.1.1.1 Example from: https://www.tutorialspoint.com/python/string_decode.htm

In [20]:
Str = "this is string example....wow!!!"
Str = Str.encode('base64','strict')

print("Encoded String: " + Str)
print("Decoded String: " + Str.decode('base64','strict')) #pendiente

LookupError: 'base64' is not a text encoding; use codecs.encode() to handle arbitrary codecs

### Return to: 1.1

In [17]:
path_data = 'sinwave.csv'

f = open(path_data, 'rb').read()
data = f.decode().split('\n')


In [18]:
type(data)

list

In [19]:
seq_len = 50
sequence_length = seq_len + 1


In [21]:
result = []
for index in range(len(data) - sequence_length):
    result.append(data[index: index + sequence_length])

result = np.array(result)

In [30]:
import numpy as np

data = np.arange(1, 72)
print(data.shape[0])
seq_len = 12
sequence_length = seq_len + 1

result = []
for index in range(len(data) - sequence_length):
    _ = data[index:index + sequence_length]
    result.append(_)
    print(_)
    
print(len(result))
    
    



71
[ 1  2  3  4  5  6  7  8  9 10 11 12 13]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 4  5  6  7  8  9 10 11 12 13 14 15 16]
[ 5  6  7  8  9 10 11 12 13 14 15 16 17]
[ 6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 9 10 11 12 13 14 15 16 17 18 19 20 21]
[10 11 12 13 14 15 16 17 18 19 20 21 22]
[11 12 13 14 15 16 17 18 19 20 21 22 23]
[12 13 14 15 16 17 18 19 20 21 22 23 24]
[13 14 15 16 17 18 19 20 21 22 23 24 25]
[14 15 16 17 18 19 20 21 22 23 24 25 26]
[15 16 17 18 19 20 21 22 23 24 25 26 27]
[16 17 18 19 20 21 22 23 24 25 26 27 28]
[17 18 19 20 21 22 23 24 25 26 27 28 29]
[18 19 20 21 22 23 24 25 26 27 28 29 30]
[19 20 21 22 23 24 25 26 27 28 29 30 31]
[20 21 22 23 24 25 26 27 28 29 30 31 32]
[21 22 23 24 25 26 27 28 29 30 31 32 33]
[22 23 24 25 26 27 28 29 30 31 32 33 34]
[23 24 25 26 27 28 29 30 31 32 33 34 35]
[24 25 26 27 28 29 30 31 32 33 34 35 36]
[25 26 27 28 

In [27]:
58 - 71

-13

i'll do it like the tutorial, but in these cases, i would think that the data should be something like: [1, 2, 3, 4], [ 4, 5, 6, 7],  [8, 9, 10, 11].. and so on for a window of size=4 elements, (i need to read the theory behind lstm)

In [31]:
import numpy as np

data = np.arange(1, 72)
print(data.shape[0])
seq_len = 12
sequence_length = seq_len + 1

size_window = 12
index_arr = np.arange(0, len(data) - size_window, size_window)

result = []
for index in index_arr:
    _ = data[index:(index + size_window)]
    result.append(_)
    print(_)
    
print(len(result))
    


71
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[13 14 15 16 17 18 19 20 21 22 23 24]
[25 26 27 28 29 30 31 32 33 34 35 36]
[37 38 39 40 41 42 43 44 45 46 47 48]
[49 50 51 52 53 54 55 56 57 58 59 60]
5


In [32]:
import numpy as np

data = np.arange(1, 72)
print(data.shape[0])
seq_len = 12
sequence_length = seq_len + 1

size_window = 4
index_arr = np.arange(0, len(data) - size_window, size_window)

result = []
for index in index_arr:
    _ = data[index:(index + size_window)]
    result.append(_)
    print(_)
    
print(len(result))
    


71
[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
[13 14 15 16]
[17 18 19 20]
[21 22 23 24]
[25 26 27 28]
[29 30 31 32]
[33 34 35 36]
[37 38 39 40]
[41 42 43 44]
[45 46 47 48]
[49 50 51 52]
[53 54 55 56]
[57 58 59 60]
[61 62 63 64]
[65 66 67 68]
17
