# LSTM Neural Network for Time Series Prediction

from: http://www.jakob-aungiers.com/articles/a/LSTM-Neural-Network-for-Time-Series-Prediction

## 1. Plot the data to learn from

The data is provided by Jakob to be downloaded from <a href="https://raw.githubusercontent.com/jaungiers/LSTM-Neural-Network-for-Time-Series-Prediction/master/sinwave.csv"> here </a>, the graph should look like the one shown below:


<img src="http://www.jakob-aungiers.com/img/article/lstm-neural-network-timeseries/sindata.png">

The code to load and plot is also provided: 

In [2]:
import numpy as np

def load_data(filename, seq_len, normalise_window):
    f = open(filename, 'rb').read()
    data = f.decode().split('\n')

    sequence_length = seq_len + 1
    result = []
    for index in range(len(data) - sequence_length):
        result.append(data[index: index + sequence_length])

    result = np.array(result)

    row = round(0.9 * result.shape[0])
    train = result[:int(row), :]
    np.random.shuffle(train)
    x_train = train[:, :-1]
    y_train = train[:, -1]
    x_test = result[int(row):, :-1]
    y_test = result[int(row):, -1]

    x_train = np.reshape(x_train, (x_train.shape[0], x_train.shape[1], 1))
    x_test = np.reshape(x_test, (x_test.shape[0], x_test.shape[1], 1))  

    return [x_train, y_train, x_test, y_test]

### 1.1 Analysing the load and plot function:

In [3]:
path_data = 'sinwave.csv'


f = open(path_data, 'rb').read()

In [4]:
type(f)

bytes

In [ ]:
f

<img src="imgs/f_info.jpeg">

#### 1.1.1 What does f.decode() ?

##### 1.1.1.1 Example from: https://www.tutorialspoint.com/python/string_decode.htm

In [20]:
Str = "this is string example....wow!!!"
Str = Str.encode('base64','strict')

print("Encoded String: " + Str)
print("Decoded String: " + Str.decode('base64','strict')) #pendiente

LookupError: 'base64' is not a text encoding; use codecs.encode() to handle arbitrary codecs

### Return to: 1.1

In [17]:
path_data = 'sinwave.csv'

f = open(path_data, 'rb').read()
data = f.decode().split('\n')


In [18]:
type(data)

list

In [19]:
seq_len = 50
sequence_length = seq_len + 1


In [21]:
result = []
for index in range(len(data) - sequence_length):
    result.append(data[index: index + sequence_length])

result = np.array(result)

In [30]:
import numpy as np

data = np.arange(1, 72)
print(data.shape[0])
seq_len = 12
sequence_length = seq_len + 1

result = []
for index in range(len(data) - sequence_length):
    _ = data[index:index + sequence_length]
    result.append(_)
    print(_)
    
print(len(result))
    
    



71
[ 1  2  3  4  5  6  7  8  9 10 11 12 13]
[ 2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 4  5  6  7  8  9 10 11 12 13 14 15 16]
[ 5  6  7  8  9 10 11 12 13 14 15 16 17]
[ 6  7  8  9 10 11 12 13 14 15 16 17 18]
[ 7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 9 10 11 12 13 14 15 16 17 18 19 20 21]
[10 11 12 13 14 15 16 17 18 19 20 21 22]
[11 12 13 14 15 16 17 18 19 20 21 22 23]
[12 13 14 15 16 17 18 19 20 21 22 23 24]
[13 14 15 16 17 18 19 20 21 22 23 24 25]
[14 15 16 17 18 19 20 21 22 23 24 25 26]
[15 16 17 18 19 20 21 22 23 24 25 26 27]
[16 17 18 19 20 21 22 23 24 25 26 27 28]
[17 18 19 20 21 22 23 24 25 26 27 28 29]
[18 19 20 21 22 23 24 25 26 27 28 29 30]
[19 20 21 22 23 24 25 26 27 28 29 30 31]
[20 21 22 23 24 25 26 27 28 29 30 31 32]
[21 22 23 24 25 26 27 28 29 30 31 32 33]
[22 23 24 25 26 27 28 29 30 31 32 33 34]
[23 24 25 26 27 28 29 30 31 32 33 34 35]
[24 25 26 27 28 29 30 31 32 33 34 35 36]
[25 26 27 28 

In [27]:
58 - 71

-13

i'll do it like the tutorial, but in these cases, i would think that the data should be something like: [1, 2, 3, 4], [ 4, 5, 6, 7],  [8, 9, 10, 11].. and so on for a window of size=4 elements for example, (i need to read the theory behind lstm)

In [31]:
import numpy as np

data = np.arange(1, 72)
print(data.shape[0])
seq_len = 12
sequence_length = seq_len + 1

size_window = 12
index_arr = np.arange(0, len(data) - size_window, size_window)

result = []
for index in index_arr:
    _ = data[index:(index + size_window)]
    result.append(_)
    print(_)
    
print(len(result))
    


71
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[13 14 15 16 17 18 19 20 21 22 23 24]
[25 26 27 28 29 30 31 32 33 34 35 36]
[37 38 39 40 41 42 43 44 45 46 47 48]
[49 50 51 52 53 54 55 56 57 58 59 60]
5


In [32]:
import numpy as np

data = np.arange(1, 72)
print(data.shape[0])
seq_len = 12
sequence_length = seq_len + 1

size_window = 4
index_arr = np.arange(0, len(data) - size_window, size_window)

result = []
for index in index_arr:
    _ = data[index:(index + size_window)]
    result.append(_)
    print(_)
    
print(len(result))
    


71
[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
[13 14 15 16]
[17 18 19 20]
[21 22 23 24]
[25 26 27 28]
[29 30 31 32]
[33 34 35 36]
[37 38 39 40]
[41 42 43 44]
[45 46 47 48]
[49 50 51 52]
[53 54 55 56]
[57 58 59 60]
[61 62 63 64]
[65 66 67 68]
17


In [33]:
import numpy as np

path_data = 'sinwave.csv'

f = open(path_data, 'rb').read()
data = f.decode().split('\n')

seq_len = 50
sequence_length = seq_len + 1

result = []
for index in range(len(data) - sequence_length):
    result.append(data[index: index + sequence_length])

result = np.array(result)

In [35]:
print(len(data))

5001


In [34]:
print(result.shape)

(4950, 51)


In [1]:
import numpy as np

path_data = 'sinwave.csv'

f = open(path_data, 'rb').read()
data = f.decode().split('\n')

seq_len = 50
sequence_length = seq_len + 1

result = []
for index in range(len(data) - sequence_length):
    result.append(data[index: index + sequence_length])

result = np.array(result)
row = round(0.9 * result.shape[0])
train = result[:int(row), :]
np.random.shuffle(train)
x_train = train[:, :-1]
y_train = train[:, -1]
x_test = result[int(row):, :-1]
y_test = result[int(row):, -1]

x_train = np.reshape(x_train, (x_train.shape[0], x_train.shape[1], 1))
x_test = np.reshape(x_test, (x_test.shape[0], x_test.shape[1], 1))  



In [4]:
import numpy as np

path_data = 'sinwave.csv'

f = open(path_data, 'rb').read()
data = f.decode().split('\n')

seq_len = 50
sequence_length = seq_len + 1

result = []
for index in range(len(data) - sequence_length):
    result.append(data[index: index + sequence_length])

result = np.array(result)

split_porcentage = 0.9

row = round(split_porcentage * result.shape[0])

train = result[:int(row), :]
np.random.shuffle(train)
x_train = train[:, :-1]
y_train = train[:, -1]
x_test = result[int(row):, :-1]
y_test = result[int(row):, -1]

x_train = np.reshape(x_train, (x_train.shape[0], x_train.shape[1], 1))
x_test = np.reshape(x_test, (x_test.shape[0], x_test.shape[1], 1))  


In [6]:
row

4455

In [7]:
x_train = train[:, :-1]
print(x_train.shape)

x_train = train[:,:]
print(x_train.shape)



(4455, 50)
(4455, 51)


In [18]:
import numpy as np

path_data = 'sinwave.csv'

f = open(path_data, 'rb').read()
data = f.decode().split('\n')

seq_len = 50
sequence_length = seq_len + 1

result = []
for index in range(len(data) - sequence_length):
    result.append(data[index: index + sequence_length])

result = np.array(result)

split_porcentage = 0.9

row = round(split_porcentage * result.shape[0])

train = result[:int(row), :]
np.random.shuffle(train)
x_train = train[:, :-1]
y_train = train[:,-1]
x_test = result[int(row):, :-1]
y_test = result[int(row):, -1]


#x_train = np.reshape(x_train, (x_train.shape[0], x_train.shape[1], 1))
#x_test = np.reshape(x_test, (x_test.shape[0], x_test.shape[1], 1))  


In [19]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)


(4455, 50)
(4455,)
(495, 50)
(495,)


In [23]:
x_train = train[:, :]
print(x_train.shape)
print(x_train[:,-1])
y_train = train[:,-1]
print(y_train.shape)
print(y_train)
#x_test = result[int(row):, :-1]
#y_test = result[int(row):, -1]


(4455, 51)
['0.688408006' '-0.688408006' '0.927808777' ..., '0.531336178'
 '0.983268329' '0.841470985']
(4455,)
['0.688408006' '-0.688408006' '0.927808777' ..., '0.531336178'
 '0.983268329' '0.841470985']


In [24]:
import numpy as np

path_data = 'sinwave.csv'

f = open(path_data, 'rb').read()
data = f.decode().split('\n')

seq_len = 50
sequence_length = seq_len + 1

result = []
for index in range(len(data) - sequence_length):
    result.append(data[index: index + sequence_length])

result = np.array(result)

split_porcentage = 0.9

row = round(split_porcentage * result.shape[0])

result.shape

#train = result[:int(row), :]
#np.random.shuffle(train)
#x_train = train[:, :-1]
#y_train = train[:,-1]
#x_test = result[int(row):, :-1]
#y_test = result[int(row):, -1]

(4950, 51)

In [25]:
result

array([['0.841470985', '0.873736397', '0.90255357', ..., '-0.7671179',
        '-0.805884672', '-0.841470985'],
       ['0.873736397', '0.90255357', '0.927808777', ..., '-0.805884672',
        '-0.841470985', '-0.873736397'],
       ['0.90255357', '0.927808777', '0.949402346', ..., '-0.841470985',
        '-0.873736397', '-0.90255357'],
       ..., 
       ['-0.725323664', '-0.7671179', '-0.805884672', ..., '0.633323869',
        '0.680666907', '0.725323664'],
       ['-0.7671179', '-0.805884672', '-0.841470985', ..., '0.680666907',
        '0.725323664', '0.7671179'],
       ['-0.805884672', '-0.841470985', '-0.873736397', ..., '0.725323664',
        '0.7671179', '0.805884672']],
      dtype='<U12')

In [32]:
result[:,0].shape

(4950,)

In [33]:
result[:,0]

array(['0.841470985', '0.873736397', '0.90255357', ..., '-0.725323664',
       '-0.7671179', '-0.805884672'],
      dtype='<U12')

In [34]:
result[0,:].shape

(51,)

In [35]:
import numpy as np

path_data = 'sinwave.csv'

f = open(path_data, 'rb').read()
data = f.decode().split('\n')

seq_len = 50
sequence_length = seq_len + 1

result = []
for index in range(len(data) - sequence_length):
    result.append(data[index: index + sequence_length])

result = np.array(result)

split_porcentage = 0.9

row = round(split_porcentage * result.shape[0])

train = result[:int(row), :]
np.random.shuffle(train)
x_train = train[:, :-1]
y_train = train[:,-1]
x_test = result[int(row):, :-1]
y_test = result[int(row):, -1]

Then, the length of the window is 50 and the element that remains (last element) is the value that lstm must predict. 
np.random.shuffle, classify the training set with the corresponding value 'y' because it is still connected as the last train element [:,:]


In [36]:
import numpy as np

path_data = 'sinwave.csv'

f = open(path_data, 'rb').read()
data = f.decode().split('\n')

seq_len = 50
sequence_length = seq_len + 1

result = []
for index in range(len(data) - sequence_length):
    result.append(data[index: index + sequence_length])

result = np.array(result)
row = round(0.9 * result.shape[0])
train = result[:int(row), :]
np.random.shuffle(train)
x_train = train[:, :-1]
y_train = train[:, -1]
x_test = result[int(row):, :-1]
y_test = result[int(row):, -1]

x_train = np.reshape(x_train, (x_train.shape[0], x_train.shape[1], 1))
x_test = np.reshape(x_test, (x_test.shape[0], x_test.shape[1], 1))  

The reshape is becouse there is only one feature for the input set and one for the <br>
output set

In [37]:
x_train.shape

(4455, 50, 1)

In [38]:
x_test.shape

(495, 50, 1)

In [39]:
import os
import time
import warnings
import numpy as np
from numpy import newaxis
from keras.layers.core import Dense, Activation, Dropout
from keras.layers.recurrent import LSTM
from keras.models import Sequential

Using TensorFlow backend.
/home/antadlp/anaconda3/envs/tensorflow/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


In [40]:

def build_model(layers):
    model = Sequential()

    model.add(LSTM(
        input_shape=(layers[1], layers[0]),
        output_dim=layers[1],
        return_sequences=True))
    model.add(Dropout(0.2))

    model.add(LSTM(
        layers[2],
        return_sequences=False))
    model.add(Dropout(0.2))

    model.add(Dense(
        output_dim=layers[3]))
    model.add(Activation("linear"))

    start = time.time()
    model.compile(loss="mse", optimizer="rmsprop")
    print("> Compilation Time : ", time.time() - start)
    
    return model

In [42]:
def predict_point_by_point(model, data):
    #Predict each timestep given the last sequence of true data, in effect only predicting 1 step ahead each time
    predicted = model.predict(data)
    predicted = np.reshape(predicted, (predicted.size,))
    return predicted

def predict_sequence_full(model, data, window_size):
    #Shift the window by 1 new prediction each time, re-run predictions on new window
    curr_frame = data[0]
    predicted = []
    for i in range(len(data)):
        predicted.append(model.predict(curr_frame[newaxis,:,:])[0,0])
        curr_frame = curr_frame[1:]
        curr_frame = np.insert(curr_frame, [window_size-1], predicted[-1], axis=0)
    return predicted

def predict_sequences_multiple(model, data, window_size, prediction_len):
    #Predict sequence of 50 steps before shifting prediction run forward by 50 steps
    prediction_seqs = []
    for i in range(int(len(data)/prediction_len)):
        curr_frame = data[i*prediction_len]
        predicted = []
        for j in range(prediction_len):
            predicted.append(model.predict(curr_frame[newaxis,:,:])[0,0])
            curr_frame = curr_frame[1:]
            curr_frame = np.insert(curr_frame, [window_size-1], predicted[-1], axis=0)
        prediction_seqs.append(predicted)
    
    return prediction_seqs

In [43]:
def load_data(filename, seq_len, normalise_window):
    f = open(filename, 'rb').read()
    data = f.decode().split('\n')

    sequence_length = seq_len + 1
    result = []
    for index in range(len(data) - sequence_length):
        result.append(data[index: index + sequence_length])

    result = np.array(result)

    row = round(0.9 * result.shape[0])
    train = result[:int(row), :]
    np.random.shuffle(train)
    x_train = train[:, :-1]
    y_train = train[:, -1]
    x_test = result[int(row):, :-1]
    y_test = result[int(row):, -1]

    x_train = np.reshape(x_train, (x_train.shape[0], x_train.shape[1], 1))
    x_test = np.reshape(x_test, (x_test.shape[0], x_test.shape[1], 1))  

    return [x_train, y_train, x_test, y_test]

In [47]:
epochs  = 30
seq_len = 50
path_data = 'sinwave.csv'

print('> Loading data... ')

X_train, y_train, X_test, y_test = load_data(path_data, seq_len, True)

print('> Data Loaded. Compiling...')

model = build_model([1, 50, 100, 1])

model.fit(
    X_train,
    y_train,
    batch_size=512,
    nb_epoch=epochs,
    validation_split=0.05)

predicted = predict_point_by_point(model, X_test)

> Loading data... 
> Data Loaded. Compiling...


/home/antadlp/anaconda3/envs/tensorflow/lib/python3.6/site-packages/ipykernel_launcher.py:8: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(input_shape=(50, 1), return_sequences=True, units=50)`
  
/home/antadlp/anaconda3/envs/tensorflow/lib/python3.6/site-packages/ipykernel_launcher.py:17: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=1)`
/home/antadlp/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/models.py:939: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


> Compilation Time :  0.015604019165039062
Train on 4232 samples, validate on 223 samples
Epoch 1/30
4232/4232 [==============================] - 2s 449us/step - loss: 0.1571 - val_loss: 0.0607
Epoch 2/30
4232/4232 [==============================] - 1s 322us/step - loss: 0.0210 - val_loss: 0.0242
Epoch 3/30
4232/4232 [==============================] - 1s 314us/step - loss: 0.0119 - val_loss: 0.0116
Epoch 4/30
4232/4232 [==============================] - 1s 309us/step - loss: 0.0159 - val_loss: 0.0038
Epoch 5/30
4232/4232 [==============================] - 1s 308us/step - loss: 0.0139 - val_loss: 0.0058
Epoch 6/30
4232/4232 [==============================] - 1s 311us/step - loss: 0.0100 - val_loss: 0.0122
Epoch 7/30
4232/4232 [==============================] - 1s 305us/step - loss: 0.0110 - val_loss: 0.0070
Epoch 8/30
4232/4232 [==============================] - 1s 314us/step - loss: 0.0123 - val_loss: 0.0066
Epoch 9/30
4232/4232 [==============================] - 1s 317us/step - loss: 

In [48]:
predicted.shape

(495,)

In [49]:
epochs  = 100
seq_len = 50
path_data = 'sinwave.csv'

print('> Loading data... ')

X_train, y_train, X_test, y_test = load_data(path_data, seq_len, True)

print('> Data Loaded. Compiling...')

model = build_model([1, 50, 100, 1])

model.fit(
    X_train,
    y_train,
    batch_size=512,
    nb_epoch=epochs,
    validation_split=0.05)

#predicted = predict_point_by_point(model, X_test)

> Loading data... 
> Data Loaded. Compiling...


/home/antadlp/anaconda3/envs/tensorflow/lib/python3.6/site-packages/ipykernel_launcher.py:8: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(input_shape=(50, 1), return_sequences=True, units=50)`
  
/home/antadlp/anaconda3/envs/tensorflow/lib/python3.6/site-packages/ipykernel_launcher.py:17: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=1)`
/home/antadlp/anaconda3/envs/tensorflow/lib/python3.6/site-packages/keras/models.py:939: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


> Compilation Time :  0.026531219482421875
Train on 4232 samples, validate on 223 samples
Epoch 1/100
4232/4232 [==============================] - 2s 469us/step - loss: 0.2041 - val_loss: 0.0557
Epoch 2/100
4232/4232 [==============================] - 1s 319us/step - loss: 0.0352 - val_loss: 0.0102
Epoch 3/100
4232/4232 [==============================] - 1s 309us/step - loss: 0.0149 - val_loss: 0.0039
Epoch 4/100
4232/4232 [==============================] - 1s 309us/step - loss: 0.0130 - val_loss: 0.0073
Epoch 5/100
4232/4232 [==============================] - 1s 316us/step - loss: 0.0130 - val_loss: 0.0015
Epoch 6/100
4232/4232 [==============================] - 1s 329us/step - loss: 0.0112 - val_loss: 0.0071
Epoch 7/100
4232/4232 [==============================] - 1s 321us/step - loss: 0.0102 - val_loss: 0.0062
Epoch 8/100
4232/4232 [==============================] - 1s 316us/step - loss: 0.0092 - val_loss: 0.0130
Epoch 9/100
4232/4232 [==============================] - 1s 313us/step

4232/4232 [==============================] - 1s 311us/step - loss: 0.0056 - val_loss: 8.3362e-04
Epoch 78/100
4232/4232 [==============================] - 1s 311us/step - loss: 0.0037 - val_loss: 0.0036
Epoch 79/100
4232/4232 [==============================] - 1s 315us/step - loss: 0.0046 - val_loss: 0.0013
Epoch 80/100
4232/4232 [==============================] - 1s 316us/step - loss: 0.0041 - val_loss: 0.0011
Epoch 81/100
4232/4232 [==============================] - 1s 314us/step - loss: 0.0036 - val_loss: 0.0015
Epoch 82/100
4232/4232 [==============================] - 1s 316us/step - loss: 0.0045 - val_loss: 0.0020
Epoch 83/100
4232/4232 [==============================] - 1s 311us/step - loss: 0.0038 - val_loss: 0.0013
Epoch 84/100
4232/4232 [==============================] - 1s 306us/step - loss: 0.0038 - val_loss: 0.0025
Epoch 85/100
4232/4232 [==============================] - 1s 309us/step - loss: 0.0042 - val_loss: 8.6839e-04
Epoch 86/100
4232/4232 [===========================

All together

In [ ]:
import matplotlib.pyplot as plt

def plot_results(predicted_data, true_data):
    fig = plt.figure(facecolor='white')
    ax = fig.add_subplot(111)
    ax.plot(true_data, label='True Data')
    plt.plot(predicted_data, label='Prediction')
    plt.legend()
    plt.show()

def plot_results_multiple(predicted_data, true_data, prediction_len):
    fig = plt.figure(facecolor='white')
    ax = fig.add_subplot(111)
    ax.plot(true_data, label='True Data')
    #Pad the list of predictions to shift it in the graph to it's correct start
    for i, data in enumerate(predicted_data):
        padding = [None for p in range(i * prediction_len)]
        plt.plot(padding + data, label='Prediction')
        plt.legend()
plt.show()